#!/usr/bin/python
import getopt
import sys
import os
from Utility import report_error, usage
from CLIModes import add_mode, close_mode, report_mode, current_mode

try:
	mode = sys.argv[1]
except Exception:
	usage()
	sys.exit(0)

if mode == "add":
	add_mode()
elif mode == "close":
	close_mode()
elif mode == "report":
	report_mode()
elif mode == "current":
	current_mode()
else:
	usage()
	report_error(1, 'Unknown mode "%s"' % mode)
